# Generated by Django 4.0.4 on 2022-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('address1', models.TextField(max_length=254)),
                ('address2', models.TextField(max_length=254)),
                ('c_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('d_name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('reg_number', models.CharField(max_length=50)),
                ('a_date', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
